### ISSUE TITLE
assign_null pattern

### ISSUE THREAD

**Issue by yegor256** [cqfn/aibolit#149]
Here it is:

```java
class Foo {
  void bar() {
    String a = null; // here
  }
}
```

Once we see `= null`, it's a pattern.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by lukyanoffpashok** [comment]
@acheshkov, I want to implement this pattern

**Comment by 0crat** [comment]
The job [#149](https://github.com/yegor256/aibolit/issues/149) assigned to @lukyanoffpashok[/z](https://www.0crat.com/u/lukyanoffpashok), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/b70afb36-2c59-4dce-a1d7-791b43e0bba1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @lukyanoffpashok[/z](https://www.0crat.com/u/lukyanoffpashok) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@lukyanoffpashok[/z](https://www.0crat.com/u/lukyanoffpashok) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by acheshkov** [comment]
@0crat wait

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@db6acc48-2b9d-4b45-9205-875832e6af9d, thread: pool-623-thread-1
com.zerocracy.radars.github.GhProject[69] com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/aibolit' repo was not found
```

[0.54.5](https://github.com/zerocracy/farm): Issue: cqfn/aibolit#149, Comment: 612461737
