### ISSUE TITLE
Method value(self, filename) in pattern classes should not accept filename

### ISSUE THREAD

**Issue by fanifieiev** [cqfn/aibolit#157]
I can see that the pattern identification classes residing in package https://github.com/yegor256/aibolit/tree/master/aibolit/patterns 
have method `value(self, filename)`, like:
So, you can use the value several times with different filenames, but I think the filename should be passed thru `__init__`, and `value` method should just rely on the passed filename.
It is actually better to make interface like abstract class, that all other pattern classes would follow.
Example:
```
class JavaAntiPattern:
    @abstractmethod
    def value(self):
        pass
```
```
class NullAntiPattern(JavaAntiPattern):
    def __init__(self, filename):
        self.filename = filename

    def value(self):
        tree = self.__file_to_ast(filename)
        return sth
```

or even with typing:
```
T = TypeVar("T")


class JavaAntiPattern(Generic[T], metaclass=ABCMeta):
    @abstractmethod
    def value(self) -> T:
        pass


class NullAntiPattern(JavaAntiPattern[list[int]]):
    def __init__(self, filename):
        self.filename = filename

    def value(self) -> list[int]:
        tree = self.__file_to_ast(self.filename)
        return ... 
```

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by lyriccoder** [comment]
1) In this case we have a lot of copy-paste code:

```
a = NullAntiPattern('File.java')
a.value()
b = NullAntiPattern('File.java')
b.value()
c = NullAntiPattern('File.java')
c.value()
c = NullAntiPattern('File.java')
c.value()
```

We should avoid it. 

2) Moreover, we need to rewrite a lot of tests for this feature. 
3) The file is not an attribute of a patterns, it's just a parameter. So, if we need to handle several files we need to create an instance of a patterns. Again,  we have lots of duplicated code. Actually, patterns is a singleton, once created it is never changed.  So, we do not need create a new object of a patterns to handle another file. We need to save this implementation:

```
a = NullAntiPattern()
a.value('Java.java')
a.value('Imple.java')
a.value('Java2.java')
```

**Comment by lyriccoder** [comment]
Not relevant anymore, we have a different API already
