### ISSUE TITLE
Make CI pipeline faster

### ISSUE THREAD

**Issue by lyriccoder** [cqfn/aibolit#202]
Merge makes from 4 up to 6 minutes. It takes too much time.
Can we make it faster?

Seems it downloads large packages every time (like pytorch etc about 900Mb)

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out  ([here](https://github.com/yegor256/aibolit/issues/202#issuecomment-612089615))

@acheshkov Job `gh:yegor256/aibolit#202` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out  ([here](https://github.com/yegor256/aibolit/issues/202#issuecomment-612089615))

@acheshkov There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 12@cf6a468ba0d0, thread: PQ-CT5UB7XAP
com.zerocracy.claims.ClaimIn[214] java.lang.IllegalArgumentException: Parameter "age" not found in "Order was canceled" among: [issue, repo, comment, job, cause, _parent_sig, flow, voluntarily, login]
```

[0.53.1](https://github.com/zerocracy/farm): CID: [eb58b2ca-7f73-4c5b-b3a9-d0801e785267](https://www.0crat.com/footprint/CT5UB7XAP/eb58b2ca-7f73-4c5b-b3a9-d0801e785267), Type: "Order was canceled"

**Comment by 0crat** [comment]
> @0crat out  ([here](https://github.com/yegor256/aibolit/issues/202#issuecomment-612089615))

@acheshkov @yegor256[/z](https://www.0crat.com/u/yegor256) resigned from [#202](https://github.com/yegor256/aibolit/issues/202), since the job is not in scope anymore

**Comment by 0crat** [comment]
The job [#202](https://github.com/yegor256/aibolit/issues/202) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/0f466c9b-bbd8-422b-af79-1984f8fd8d43); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by lyriccoder** [comment]
Nobody cares, I will close it

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@db6acc48-2b9d-4b45-9205-875832e6af9d, thread: pool-474-thread-1
com.zerocracy.radars.github.GhProject[69] com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/aibolit' repo was not found
```

[0.54.5](https://github.com/zerocracy/farm): Issue: cqfn/aibolit#202, Comment: 612089615
