### ISSUE TITLE
Fix 0pdd issue on build

### ISSUE THREAD

**Issue by paulodamaso** [cqfn/aibolit#255]
There is a 0pdd error that is happening in build, probably a puzzle with wrong format. We should fix it and add pdd execution to merge and build scripts so it does not happen again

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#255](https://github.com/yegor256/aibolit/issues/255) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/6c49eb15-1085-4a82-b34f-a749759c7f17); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by yegor256** [comment]
@paulodamaso fixed in 76b6e4e

**Comment by paulodamaso** [comment]
@yegor256 we can't exclude  `'test` folder, there are a lot of puzzled inside it

**Comment by yegor256** [comment]
@paulodamaso it's fixed, thanks

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@db6acc48-2b9d-4b45-9205-875832e6af9d, thread: pool-474-thread-1
com.zerocracy.radars.github.ReSafe[81] java.io.IOException: com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/aibolit' repo was not found
com.zerocracy.radars.github.GhProject[69] com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/aibolit' repo was not found
```

[0.54.5](https://github.com/zerocracy/farm): Issue: cqfn/aibolit#255, Action: `created`
