### ISSUE TITLE
Null check (P13): false positive

### ISSUE THREAD

**Issue by yegor256** [cqfn/aibolit#369]
This is my Java code:

```java
public boolean exists(final String name) {
  return this.get(name) != null;
}
```

Obviously, I'm not _checking_ for NULL here.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by lyriccoder** [comment]
what is wrong here? `!= null` is checking for null. We have discussed it, `Null check pattern` as it is
