### ISSUE TITLE
SendNull pattern has errors

### ISSUE THREAD

**Issue by lyriccoder** [cqfn/aibolit#406]
files.tar.gz - files with 

errors
[files.tar.gz](https://github.com/yegor256/aibolit/files/4763540/files.tar.gz)

Errors:

'SuperMethodInvocation' object has no attribute '_position'
'SuperConstructorInvocation' object has no attribute '_position'
'ExplicitConstructorInvocation' object has no attribute '_position'

Full log is here:

[errors.txt](https://github.com/yegor256/aibolit/files/4763550/errors.txt)

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`
