### ISSUE TITLE
Survey Description

### ISSUE THREAD

**Issue by acheshkov** [cqfn/aibolit#416]
Maintainability Survey
---

Hi, 

We are doing the research and want to find a group of respondents to participate in a survey. 
We are going to pay for the time you spent. But before participating in the big survey we'd like to ask you to do the smaller version of the same survey to match your 
profile with our expectations of respondents.   

Survey details
---

In this survey, we ask you to rate `Modifiability`, `Testability` and `Readability` 
of each Java class in accordance with the following scale: `0` - easy; `1`- hard.

The example of the table we expect to see:

| FileName | Modifiability | Testability | Readability
|--------|-----------|--------|--------------------|
|DefaultDispatcherRunnerFactory.java|0|0|1|
|KafkaConsumerManager.java|1|1|0
|DispatcherHandlerMappingDescription.java|1|0|1

We are aware that your judgment is highly subjective and greatly
depends on the experience. Please try to rate the classes according
to your own perceptions, don't overthink it.

Please rate the Java classes from the `java_classes` folder, fill the enclosed CSV file, 
and email it back to us. The name of the file has to follow the format: `YourFirstLastName_survey_tmpl.csv`.

Also, please answers the following questions:

1. How long you have been programming in Java?
2. How long you have been programming including all languages?

Please find the Java classes and CSV template in the attached zip archive.

**Comment by lyriccoder** [comment]
[maintenanability_survey.zip](https://github.com/yegor256/aibolit/files/4793646/maintenanability_survey.zip)

**Comment by 0crat** [comment]
I'm not managing `cqfn/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
