### ISSUE TITLE
Add Fan Out metric

### ISSUE THREAD

**Issue by Vitaly-Protasov** [cqfn/aibolit#450]
https://checkstyle.sourceforge.io/config_metrics.html#ClassFanOutComplexity

http://www.virtualmachinery.com/jhawkmetricsclass.htm

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You @vitaly-protasov[/z](https://www.0crat.com/u/vitaly-protasov) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project
