### ISSUE TITLE
Aibolit API to get patterns and metrics statistics table

### ISSUE THREAD

**Issue by acheshkov** [cqfn/aibolit#459]
I want to be able to get a table as we have across our patterns using as simple as the following pseudo-code bellow

```python
import  aibolit_stat from aibolit

test_dataset_csv = pd.read_csv('...')
table = aibolit_stat (test_dataset_csv)

print(table)

```

**Comment by 0crat** [comment]
The job [#459](https://github.com/yegor256/aibolit/issues/459) assigned to @lyriccoder[/z](https://www.0crat.com/u/lyriccoder), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/136e3a4b-621a-4290-a97b-9bb633e831bc); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job
