### ISSUE TITLE
SuppressWarnings annotation support

### ISSUE THREAD

**Issue by g4s8** [cqfn/aibolit#462]
JDK has source annotation to suppress any warnings: `@SupressWarnings`: https://docs.oracle.com/javase/8/docs/api/java/lang/SuppressWarnings.html Many linters (like javac or PMD) suppores this annotation to ignore warning, e.g.
```java
@SuppressWarnings("PMD.ProhibitPublicStaticMethods")
public static void foo() { }
```
In java code will suppress public static method PMD warning. It's the standard way to ignore warnings for Java linters and checkers.

I'd suggest supporting this annotation for Aibolit to suppress warnings for classes methods and variables, it may use "aibolit" prefix to separate from other suppression, like:
```java
@SuppressWarnings("aibolit.P22")
public void foo(byte[] array) { }
```

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by yegor256** [comment]
@acheshkov @g4s8 definitely a feature we need!

**Comment by 0crat** [comment]
I'm not managing `cqfn/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ceb75b72-5128-4a32-a6a0-db018bc785eb, thread: pool-409-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to cqfn/aibolit#462: I'm not managing `cqfn/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](
```

[0.53.15](https://github.com/zerocracy/farm): Issue: cqfn/aibolit#462, Action: `closed`
