### ISSUE TITLE
Regression testing.

### ISSUE THREAD

**Issue by aravij** [cqfn/aibolit#467]
Despite of unit tests, we need ability to test all patterns against large number of source codes and fix their behavior.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@8366e303-9dc5-4679-a29a-c61b61f06cfb, thread: PQ-CT5UB7XAP
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Evaluate pattern on arbitary AST' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [9ee95629-c17e-4fba-9a85-140bf3f98d9f](https://www.0crat.com/footprint/CT5UB7XAP/9ee95629-c17e-4fba-9a85-140bf3f98d9f), Type: "Job milestoned"

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @aravij[/z](https://www.0crat.com/u/aravij) are: `DEV`, `REV`

**Comment by lukyanoffpashok** [comment]
[report_patterns.pdf](https://github.com/cqfn/aibolit/files/4879861/report_patterns.pdf)

**Comment by lukyanoffpashok** [comment]
In case of 2 snippets there were nan in implementing with refactoring

**Comment by lukyanoffpashok** [comment]
In other patterns (exclude "Return null", "Multiple While", metric "ncss") there were mistakes (< 6 %)

**Comment by aravij** [comment]
Great! I would also consider patterns with near 5% a case for research. So now we have following tasks:
 - [ ] Find out reason for getting `NaN` on those two snippets
 - [ ] Research "Multiple While" pattern for significant changes
 - [ ] If we have time, take a look for "Joined validation" and "ForceTypeCastingFinder" patterns.
I think I can take care of it.
