### ISSUE TITLE
AST API refactoring.

### ISSUE THREAD

**Issue by aravij** [cqfn/aibolit#469]
Refactoring plan:

- [x]  Move all ast relative modules to separate package
- [x] Add all `javalang` fields to `netwrokx` graph as attributes; remove auxiliary methods from `AST` class; simplify refactored patterns
- [x] Add proxy object for ast nodes, to hide out `networkx` API, and provide more convenient API, more close to `javalang`

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@8366e303-9dc5-4679-a29a-c61b61f06cfb, thread: PQ-CT5UB7XAP
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Evaluate pattern on arbitary AST' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [1a06d7d2-1fa1-479f-a9bd-5140056646c9](https://www.0crat.com/footprint/CT5UB7XAP/1a06d7d2-1fa1-479f-a9bd-5140056646c9), Type: "Job milestoned"

**Comment by 0crat** [comment]
I'm not managing `cqfn/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by aravij** [comment]
Currently polishing the work.
