### ISSUE TITLE
Fix filter function to allow split dataset by filenames

### ISSUE THREAD

**Issue by lyriccoder** [cqfn/aibolit#480]
We need to set test part and train par for dataset before model is loaded.
We will split the dataset when we have only filenames.

It's a part of https://github.com/cqfn/aibolit/issues/459

**Comment by 0crat** [comment]
@lyriccoder[/z](https://www.0crat.com/u/lyriccoder) I'm not managing this repo, remove the [webhook](https://github.com/cqfn/aibolit/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `cqfn/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `cqfn/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@740afc52-4253-4b74-b664-43aa471040ba, thread: pool-1177-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to cqfn/aibolit#480: I'm not managing `cqfn/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](
```

[0.53.15](https://github.com/zerocracy/farm): Issue: cqfn/aibolit#480, Action: `closed`
