### ISSUE TITLE
Decrease connection timeout

### ISSUE THREAD

**Issue by acheshkov** [cqfn/aibolit#491]
If there are no internet Aibolit stuck several minutes before return the version

```
root@xxx:~# aibolit --version
Can't check aibolit version. Network is not available
aibolit 1.1.2
root@xxx:~#
```
1. Decrease connection timeout 
2. And improve output. It is confusing.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) I'm not managing this repo, remove the [webhook](https://github.com/cqfn/aibolit/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `cqfn/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `cqfn/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by lyriccoder** [comment]
And improve output. It is confusing?
What is it necessary to improve? It is not clear. Could you please  explain or provide a solution/example?
