### ISSUE TITLE
Function to find start and end lines for a node

### ISSUE THREAD

**Issue by lyriccoder** [cqfn/aibolit#495]
need to write Function to find start and end lines for a node
part of #462

**Comment by 0crat** [comment]
@lyriccoder[/z](https://www.0crat.com/u/lyriccoder) I'm not managing this repo, remove the [webhook](https://github.com/cqfn/aibolit/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `cqfn/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `cqfn/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@16c0dd3a-692b-42f2-8183-1fd13c0b91de, thread: pool-864-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to cqfn/aibolit#495: I'm not managing `cqfn/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](
```

[0.53.15](https://github.com/zerocracy/farm): Issue: cqfn/aibolit#495, Action: `closed`
