### ISSUE TITLE
Create function for finding annotations

### ISSUE THREAD

**Issue by lyriccoder** [cqfn/aibolit#500]
1) Create test which will show how to use `@SuppressWarnings` to ignore patterns
2) Create function for finding annotations for FieldDeclaration, MethodDeclaration, ClassDeclaration which is supported at the moment

**Comment by 0crat** [comment]
@lyriccoder[/z](https://www.0crat.com/u/lyriccoder) I'm not managing this repo, remove the [webhook](https://github.com/cqfn/aibolit/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `cqfn/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `cqfn/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
