### ISSUE TITLE
Create function to filter ignored lines

### ISSUE THREAD

**Issue by lyriccoder** [cqfn/aibolit#502]
Create function to filter ignored lines
It's a part of #462

**Comment by 0crat** [comment]
@lyriccoder[/z](https://www.0crat.com/u/lyriccoder) I'm not managing this repo, remove the [webhook](https://github.com/cqfn/aibolit/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `cqfn/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `cqfn/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
