### ISSUE TITLE
--exclude doesn't work: crashes with exception

### ISSUE THREAD

**Issue by yegor256** [cqfn/aibolit#507]
```
$ aibolit check --folder=src/main '--exclude=**/Xembler.java'
Version 1.2.3rc1 is available, but you are using 1.1.2
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aibolit/__main__.py", line 611, in main
    exit_code = run_parse_args(commands)
  File "/usr/local/lib/python3.7/site-packages/aibolit/__main__.py", line 99, in run_parse_args
    return commands_dict[args.command]()
  File "/usr/local/lib/python3.7/site-packages/aibolit/__main__.py", line 607, in <lambda>
    'check': lambda: check(),
  File "/usr/local/lib/python3.7/site-packages/aibolit/__main__.py", line 483, in check
    files_to_exclude = handle_exclude_command_line(args)
  File "/usr/local/lib/python3.7/site-packages/aibolit/__main__.py", line 524, in handle_exclude_command_line
    raise Exception(exc_string)
Exception: Usage: --exclude=<glob pattern> --exclude=<glob pattern> ... --exclude=folder_to_find_exceptions
```

**Comment by lyriccoder** [comment]
It is written: 
Exception: Usage: --exclude=<glob pattern> --exclude=<glob pattern> ... --exclude=folder_to_find_exceptions

The first parameter is glob pattern, the second one is folder to find exceptions. 

No issue here

**Comment by yegor256** [comment]
@lyriccoder I don't understand at all. `--exclude` is supposed to specify glob pattern to exclude files from the `--folder`. I'm specifying the folder and then a list of "excludes":

```
$ aibolit check --folder=src/main --exclude=**/*Test.java --exclude=**/*ITCase.java
```

This is how "exclude" works in all tools I know :)

**Comment by yegor256** [comment]
@lyriccoder it seems you are mixing `--exclude` with `--ignore`, don't you?)

**Comment by lyriccoder** [comment]
We discussed such the behaviour by phone, we have even such the description in the docs

**Comment by yegor256** [comment]
@lyriccoder yes, `--folder` is where my files are, but `--exclude` is the glob pattern to apply to the search, in order to exclude some files from my folder.

**Comment by lyriccoder** [comment]
https://github.com/cqfn/aibolit/issues/363
You described it here, you forgot it already

**Comment by yegor256** [comment]
@lyriccoder I made a mistake in the spec, sorry. `--exclude` should accept just a list of glob patterns and exclude them all. That's it. The folder should still be provided in the `--folder` parameter. Can we please fix this?

**Comment by lyriccoder** [comment]
Can we choose another parameter? I see people are using it for a different case. They are searching java files there.

I see that @g4s8  is using `--folder`, but not `--filenames`. Moreover, we should leave a way to use `--folder` for Windows users

**Comment by lyriccoder** [comment]
fixed, closing
