### ISSUE TITLE
P13 suppression doesn't work

### ISSUE THREAD

**Issue by yegor256** [cqfn/aibolit#514]
This is the build: https://travis-ci.org/github/yegor256/xembly/builds/707883888 You can see that the bug is in `UpDirective`. However, there is a suppression: https://github.com/yegor256/xembly/blob/master/src/main/java/org/xembly/UpDirective.java#L53

Looks like the suppression doesn't work?

**Comment by yegor256** [comment]
@lyriccoder fixed?

**Comment by lyriccoder** [comment]
@yegor256, yes, it is fixed.
