### ISSUE TITLE
NCSS metric discussion.

### ISSUE THREAD

**Issue by aravij** [cqfn/aibolit#538]
Let us discuss and state how do we calculate NCSS metric, how it differ from `PMD` variant and so on.
Current variant of metric calculation:
 - **+1** for each of the following keyword:
   - `assert`
   - `break`
   - `catch`
   - `continue`
   - `do` (`do ... while();`)
   - `for`
   - `if`
   - `return`
   - `switch`
   - `case` (`switch .... case():`)
   - `synchronize`
   - `throw`
   - `while`
   - 'else'
   - 'finally'
 - **+1** for types declaration:
   - annotation
   - class
   - constant
   - enum constant (_no idea what it is!_)
   - enum
   - interface
 - **+1** for declarations inside class:
   - constructor
   - method
   - field
- **+1** for declaring local variables (several declaration in one line counts as one), excluding variables declared in `for` loops
- **+1** for each statement expression
- **+1** for _TYPE_DECLARATION_, it is a `AST` node type and I think it is actually never appear in real `AST` (I will probably remove it)

Differences from PMD (https://pmd.github.io/latest/pmd_java_metrics_index.html#non-commenting-source-statements-ncss):
 - we count `assert`. In PMD they count it in the example, but not in text description

Questions:
 - Neither PMD nor we count `try` statements. Should we?
 - Does `else if` should add **+1** or **+2** to metric? Currently it adds **+1**.

**Comment by acheshkov** [comment]
What is the difference between `+1 for each statement expression` and `+1 for each of the keyword FOR`?

**Comment by aravij** [comment]
In our code there is node type `STATEMENT_EXPRESSION`, so we make an easy difference.
In a Java code a statement expression seamed to me an expression with `;` on the end. It could be an assignment or method call or something like this. I can find out how often this node is appeared and what kind of children may it have.

**Comment by aravij** [comment]
Just to mention it here.
Following node types were never met in all integration test files:
 - CREATOR
 - DECLARATION
 - DOCUMENTED
 - EXPRESSION
 - INVOCATION
 - MEMBER
 - PRIMARY
 - TYPE
 - TYPE_DECLARATION

All this nodes are used in `javalang` as intermediate classes in class hierarchy. It seems like those nodes shouldn't be used in code analysis. I will remove TYPE_DECLARATION from types on which  we increment NCSS metric.

For node `STATEMENT_EXPRESSION`, it has following node types as children:
 - ASSIGNMENT
 - CAST
 - CLASS_CREATOR
 - CLASS_REFERENCE
 - EXPLICIT_CONSTRUCTOR_INVOCATION
 - LITERAL
 - MEMBER_REFERENCE
 - METHOD_INVOCATION
 - SUPER_CONSTRUCTOR_INVOCATION
 - SUPER_METHOD_INVOCATION
 - TERNARY_EXPRESSION
 - THIS

@acheshkov This should give you a clue, what `STATEMENT_EXPRESSION` may be in source code.

**Comment by aravij** [comment]
Considering question, I think to count both `assert` and `try` statements to increment NCSS and count `if else` statement as **single** increment.
Any thoughts?

**Comment by aravij** [comment]
@acheshkov @lyriccoder I decided to create a PR #559 with differences to NCSS metric I propose.
